
# apiVersion - Kubernetes API version
# kind - the type of object you want to create
# metadata - info about the object so that it can be uniquely identified
# spec - desired state of the object
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdeploy
  labels:
    app: flask
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flask
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '5000'
    spec:
      containers:
      - name: flask
        image: moditamam/1208:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
